name: Java CI with gradle (based on https://github.com/hexlet-boilerplates/java-package/blob/main/.github/workflows/main.yml)

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
      - run: .gradlew checkstyleMain
      - run: .gradlew test
