name: Java CI with gradle (based on https://github.com/hexlet-boilerplates/java-package/blob/main/.github/workflows/main.yml)

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
      - run: ./gradlew checkstyleMain
      - run: ./gradlew test

      #- run: make install
      #- run: make lint
      #- run: make test
      #- uses: hexlet-components/hello-from-hexlet-action@release

name: Publish code coverage
      uses: paambaati/codeclimate-action@v9.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_ID}}
        JACOCO_SOURCE_PATH: /app/src/main/java
      with:
         coverageCommand: make report
         coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
