name: Java CI with gradle and CodeClimate

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # run tests and jacoco coverage report
      - run:
          name: Gradle build
          command: ./gradlew clean build jacocoTestReport

      # set up xml path for code climate
      - run:
          name: Set jacoco.xml path for code climate
          command: JACOCO_SOURCE_PATH=app/src/main ./cc-test-reporter format-coverage ./build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco

      # upload coverage on code climate
      - run:
          name: Upload code climate report
          command: ./cc-test-reporter upload-coverage -r ${{secrets.CC_TEST_REPORTER_ID}}
          when: on_success
